db/__init__.py
from .projects import add_project, get_projects, get_project_by_id, get_project_by_uuid, update_project_pipeline
from .jobs import get_jobs
from .init import init_db

lib/__init__.py
from .decorators import public_endpoint

lib/app.py
from flask import session, request, redirect

from db.init import init_db
from lib.get_env import get_env, MINIM_FLASK_APP_SECRET_KEY
from lib.gitlab import gitlab_get_personal_token
from routes import auth_blueprint, main_blueprint, settings_blueprint, projects_blueprint, hooks_blueprint


def config_app(app):
    app.config['SECRET_KEY'] = get_env(MINIM_FLASK_APP_SECRET_KEY)

    # init and configure
    init_db()

    @app.context_processor
    def inject_gitlab_token_info():
        return dict(no_gitalb_token=not gitlab_get_personal_token())

    @app.before_request
    def check_valid_login():
        login_valid = 'user' in session  # or whatever you use to check valid login

        if (request.endpoint and
                'static' not in request.endpoint and
                not login_valid and
                not getattr(app.view_functions[request.endpoint], 'is_public', False)):
            return redirect('/login?next=' + request.path)

    # blueprint for main routes in our app
    app.register_blueprint(main_blueprint)

    # blueprint for auth routes in our app
    app.register_blueprint(auth_blueprint)

    # blueprint for settings routes in our app
    app.register_blueprint(settings_blueprint)

    # blueprint for settings routes in our app
    app.register_blueprint(projects_blueprint)

    # blueprint for settings routes in our app
    app.register_blueprint(hooks_blueprint)

    return app

lib/jobs_runner/__init__.py
from .runner import JobsRunner

routes/__init__.py
from .auth import auth as auth_blueprint
from .main import main as main_blueprint
from .settings import settings as settings_blueprint
from .projects import projects as projects_blueprint
from .hooks import hooks as hooks_blueprint

routes/auth.py
from flask import Blueprint, request, session, render_template, redirect

from lib import public_endpoint
from lib.get_env import get_env, MINIM_AUTH_KEY

auth = Blueprint('auth', __name__)


@public_endpoint
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        if request.form.get('token') == get_env(MINIM_AUTH_KEY):
            session['user'] = 'ok'
            next_url = request.form.get('next_url')
            return redirect(next_url or '/')

    return render_template('login.html', next=request.args.get('next'))


@auth.route('/logout')
def logout():
    if 'user' in session:
        del session['user']
    return redirect('/')

routes/hooks.py
from flask import Blueprint, request

from lib import public_endpoint
from lib.gitlab import gitlab_get_webhook_token

hooks = Blueprint('hooks', __name__)


# TODO trigger project build
@public_endpoint
@hooks.route('/hook', methods=["POST", "GET"])
def hook():
    token = request.headers.get('X-Gitlab-Token')
    if not (token == gitlab_get_webhook_token()):
        return dict(ok=False), 401
    return dict(ok=True)

routes/main.py
from flask import Blueprint, redirect

main = Blueprint('main', __name__)


@main.route('/', methods=["GET"])
def index():
    return redirect('/projects')

routes/projects.py
import json

from flask import Blueprint, render_template, request, redirect

from db import add_project, get_projects, get_project_by_id, update_project_pipeline
from lib.gitlab import gitlab_get_project, gitlab_get_project_branches
from lib.jobs import TYPES_DESCRIPTION

projects = Blueprint('projects', __name__)


@projects.route('/projects', methods=["POST", "GET"])
def index():
    error = None
    if request.method == "POST":
        project_path_with_namespace = request.form.get('path_with_namespace')
        print(">>>>>>>>>>>>>>>>>>>>>>")
        print(project_path_with_namespace)
        if not project_path_with_namespace:
            error = "No project selected"
        else:
            err, project = gitlab_get_project(project_path_with_namespace)
            if err:
                error = json.dumps(err)
            else:
                add_project(project)

    projects_list = get_projects()

    return render_template('index.html', projects=projects_list, error=error)


@projects.route('/projects/<id>')
def project(id, err=None):
    from lib.jobs import TYPES
    project = get_project_by_id(id)
    if not project:
        return render_template('404.html')
    error, branches = gitlab_get_project_branches(id)
    if not branches:
        branches = []
    return render_template('project.html', project=project, branches=branches, types=json.dumps(TYPES),
                           typesDescription=json.dumps(TYPES_DESCRIPTION), error=error or err)


@projects.route('/projects/<id>/pipeline', methods=["POST"])
def pipeline(id):
    steps = request.form.get('steps')
    env = request.form.get('envs')
    branch = request.form.get('branch')
    if not steps:
        return project(id, "No steps defined for the project")

    update_project_pipeline(id, branch, steps, env)

    return redirect('/projects/' + id)


@projects.route('/projects/<id>/run-pipeline', methods=["POST"])
def run_pipeline(id):
    from lib.socket import send_io_message
    send_io_message('test')
    from lib.jobs_runner import JobsRunner
    project = get_project_by_id(id)
    r = JobsRunner()
    r.run(project)
    return redirect('/projects/' + id)

routes/settings.py
from flask import Blueprint, render_template, request, redirect

from lib.gitlab import gitlab_set_personal_token, gitlab_get_personal_token, gitlab_set_webhook_token

settings = Blueprint('settings', __name__)


@settings.route('/settings', methods=['GET', 'POST'])
def index():
    if request.method == "POST":
        gitlab_personal_token = request.form.get('gitlab_personal_token')
        if gitlab_personal_token is not None:
            gitlab_set_personal_token(gitlab_personal_token)

        gitlab_webhook_token = request.form.get('gitlab_webhook_token')
        if gitlab_webhook_token is not None:
            gitlab_set_webhook_token(gitlab_webhook_token)

        return redirect('/')

    return render_template('settings.html', token=gitlab_get_personal_token())

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Minim</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
    <style>
        body, html {
            font-family: monospace;
        }

        .logo {
            padding-left: 0;
        }
    </style>
</head>

<body>
<section class="hero is-fullheight">
    <div class="hero-head">
        <nav class="navbar">
            <div class="container">
                <a href="{{ url_for('main.index') }}" class="logo navbar-item">
                    Minim
                </a>
                {% if no_gitalb_token %}
                <a href="{{ url_for('settings.index') }}" class="navbar-item has-text-danger">
                    * please setup the gitlab auth token
                </a>
                {% endif %}
                <div id="navbarMenuHeroA" class="navbar-menu  is-primary">
                    <div class="navbar-end">

                        <a href="{{ url_for('settings.index') }}" class="navbar-item">
                            Settings
                        </a>
                        {% if not session.user %}
                        <a href="{{ url_for('auth.login') }}" class="navbar-item">
                            Log in
                        </a>
                        {% else %}
                        <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                            Log out
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <div class="hero-body">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <div class="container">
        <footer>
            <div class="p-1">
                A 380SQ Product
            </div>
        </footer>
    </div>
</section>
<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"
        integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8">
    let socket = io();
    window.HUB = {
        cbs: {},
        on(action, cb) {
            if (!HUB.cbs[action]) {
                HUB.cbs[action] = [];
            }
            HUB.cbs[action].push(cb)

        },
        fire(action, payload) {
            if (HUB.cbs[action]) {
                HUB.cbs[action].forEach(fn => {
                    fn(payload);
                })
            }
        }
    };
    socket.on('connect', function () {
        console.log("socket is connected")
    });
    socket.on('message', function (data) {
        window.HUB.fire(data.event, data.payload);
    });
</script>
</body>

</html>

templates/docs.html
{% extends "base.html" %}

{% block content %}

<div class="column is-4 is-offset-4">
    {% if error %}
    <span class="has-text-danger has-text-centered">{{error}}</span>
    {% endif %}
    <form method="POST" action="/projects">
        <div class="field">
            <div class="control">

                <input class="input is-large" type="text" name="path_with_namespace" placeholder="project url "
                       autofocus=""
                       autocomplete="false">
            </div>
        </div>
        <button class="button is-block is-info is-large is-fullwidth">Add new project</button>
    </form>
</div>

<h2>Projects</h2>
{% for e in projects %}
<div>
    <a href="/projects/{{e.id}}"> {{ e.name }} </a>
</div>
{% endfor %}

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="column is-4 is-offset-4">
    {% if error %}
    <span class="has-text-danger has-text-centered">{{error}}</span>
    {% endif %}
    <form method="POST" action="/projects">
        <div class="field">
            <div class="control">

                <input class="input is-large" type="text" name="path_with_namespace" placeholder="project url "
                       autofocus=""
                       autocomplete="false">
            </div>
        </div>
        <button class="button is-block is-info is-large is-fullwidth">Add new project</button>
    </form>
</div>

<h2>Projects</h2>
{% for e in projects %}
<div>
    <a href="/projects/{{e.id}}"> {{ e.name }} </a>
</div>
{% endfor %}

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        <form method="POST" action="/login">
            <input type="hidden" value="{{ next_url }}" name="next">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="token" placeholder="Token" autofocus="">
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

templates/project.html
{% extends "base.html" %}

{% block content %}
<style>
    #steps_container > div, #env_container > div {
        margin: 5px 0;
    }
</style>
<form action="{{ url_for('projects.run_pipeline', id=project.id) }}" method="post">
    <h1 class="is-size-2">Project : {{project.name}} <span id="running_status" class="tag is-hidden is-danger is-small">Running {% include 'includes/spinner.svg' %}</span>
    </h1>
    <button type="submit" id="run_pipeline" class="is-pulled-right button is-danger">Run</button>
</form>
<form action="{{ url_for('projects.pipeline', id=project.id) }}" method="post">
    <input type="hidden" id="steps_types_description" value="{{typesDescription}}">
    <input type="hidden" id="steps_types" value="{{types}}">
    <input type="hidden" id="steps_values" name="steps" value="{{project.pipeline_steps}}">
    <input type="hidden" id="envs_values" name="envs" value="{{project.pipeline_envs}}">
    <label for="branch" class="is-size-5">Branch</label>
    {% if error %}
    <span class="is-danger">{{error}}</span>
    {% endif %}
    <select id="branch" name="branch" class="select">
        {% for branch in branches %}
        <option value="{{branch.name}}">
            {{branch.name}}
        </option>
        {% endfor %}
    </select>
    <h4 class="is-size-5">Steps
        <small class="is-size-7"> Steps to be build</small>
    </h4>
    <div id="steps_container">

    </div>

    <button id="add_step" class="button primary  is-small is-primary">+ Add step</button>
    <hr/>

    <h4 class="is-size-5">Env
        <small class="is-size-7"> Env variables to be passed to steps</small>
    </h4>
    <div id="env_container">

    </div>

    <button id="add_env" class="button primary  is-small is-primary">+ Add Env</button>
    <hr/>
    <button id="form_submit" type="submit" class="button is-primary">Save</button>
</form>
<script>
    // TOOLS
    // get types of steps and helpers (placeholders )
    const typesDescription = JSON.parse(document.getElementById('steps_types_description').value);

    function createFieldElement(tag, className, fieldClassName) {
        const field = document.createElement('div');
        if (fieldClassName) {
            field.classList.add(fieldClassName)
        } else {
            field.classList.add('field');
        }
        let control = document.createElement('p');
        control.classList.add('control');
        field.appendChild(control);
        let element = document.createElement(tag);
        control.appendChild(element);
        element.classList.add(tag);
        if (className) {
            element.classList.add(className);
        }
        return {
            field: field,
            element: element
        }
    }

    function createFieldBodyElement(isHorizontal) {
        const fieldBody = document.createElement('div');
        fieldBody.classList.add('field-body');
        if (isHorizontal) {
            fieldBody.classList.add("is-horizontal");
        }
        return fieldBody;
    }

    function getJobDescription(select) {
        let selected = select.options[select.selectedIndex].value;
        return typesDescription[selected] || '';
    }

</script>
<script>
    // HANDLE STEPS
    let actions = JSON.parse(document.getElementById('steps_types').value);
    const STEP_KIND_CLASS = "step-key";
    const STEP_KIND_SUFFIX = "step_value_";

    function createPipelineStep(ele /* if already exists  */) {
        let row = createFieldBodyElement(true);
        let selectField = createFieldElement('select', STEP_KIND_CLASS);
        let select = selectField.element;
        let textField = createFieldElement('textarea');
        let deleteField = createFieldElement('button', NaN, 'is-pulled-right');
        let text = textField.element;
        let container = document.getElementById('steps_container');
        let selects = container.querySelectorAll('.' + STEP_KIND_CLASS);
        let optionEl;
        actions.forEach(e => {
            optionEl = document.createElement('option');
            optionEl.setAttribute('value', e);
            optionEl.innerText = e;
            if (ele) {
                if ((ele.type) === e) {
                    optionEl.setAttribute('selected', 'selected');
                }
            }
            select.appendChild(optionEl);
        });
        let id;
        if (ele) {
            id = STEP_KIND_SUFFIX + ele.index;
            text.value = ele.value;

        } else {
            id = STEP_KIND_SUFFIX + selects.length;
        }
        select.setAttribute('data-value-id', id);
        text.setAttribute('id', id);
        row.appendChild(selectField.field);
        row.appendChild(textField.field);
        row.appendChild(deleteField.field);
        container.appendChild(row);
        select.addEventListener('change', function (event) {
            text.placeholder = getJobDescription(event.currentTarget);
        });
        if (!ele) {
            text.placeholder = getJobDescription(select);
        }
        deleteField.element.innerText = "X";
        deleteField.element.addEventListener('click', function (event) {
            container.removeChild(row);
        })
    }

    function getSteps() {
        let steps = [];
        let selects = document.querySelectorAll('.' + STEP_KIND_CLASS);
        selects.forEach((e, index) => {
            steps.push({
                index: index,
                type: e.value,
                value: document.getElementById(e.dataset.valueId).value
            });

        });
        return steps;
    }

    let button = document.getElementById('add_step');
    button.addEventListener('click', function (event) {
        event.preventDefault();
        createPipelineStep();
    })

</script>
<script>
    // HANDLE ENV KEYS
    const ENV_KEY_CLASS = "env-key";
    const ENV_VALUE_SUFFIX = "env_value_";

    function createEnvRow(ele /* if ele already exists */) {
        let elements = document.querySelectorAll('.' + ENV_KEY_CLASS);
        let container = document.getElementById('env_container');
        let row = createFieldBodyElement(true);
        let fieldName = createFieldElement('input', ENV_KEY_CLASS);
        let fieldValue = createFieldElement('input');
        let deleteField = createFieldElement('button', NaN, 'is-pulled-right');
        let inputName = fieldName.element;
        let inputValue = fieldValue.element;
        let id;
        if (ele) {
            id = ENV_VALUE_SUFFIX + ele.index;
            inputName.value = ele.key;
            inputValue.value = ele.value;
        } else {
            id = ENV_VALUE_SUFFIX + elements.length;
        }
        inputName.setAttribute('data-value-id', id);
        inputValue.setAttribute('id', id);
        row.appendChild(fieldName.field);
        row.appendChild(fieldValue.field);
        row.appendChild(deleteField.field);
        container.appendChild(row);
        deleteField.element.innerText = "X";
        deleteField.element.addEventListener('click', function (event) {
            container.removeChild(row);
        })
    }

    function getEnvs() {
        let envs = [];
        let inputs = document.querySelectorAll('.' + ENV_KEY_CLASS);
        inputs.forEach((e, index) => {
            if (e.value) {
                envs.push({
                    index: index,
                    key: e.value,
                    value: document.getElementById(e.dataset.valueId).value
                });
            }

        });
        return envs;
    }

    let buttonEnv = document.getElementById('add_env');
    buttonEnv.addEventListener('click', function () {
        event.preventDefault();
        createEnvRow();
    })

</script>

<script>
    // Init function
    let stepsInput = document.getElementById('steps_values');
    let envsInputs = document.getElementById('envs_values');
    // init steps
    try {
        let stepsValue = stepsInput.value;
        if (stepsValue && stepsValue !== "None") {
            let steps = JSON.parse(stepsValue);
            steps.forEach(e => {
                createPipelineStep(e)
            })
        }
    } catch (e) {

        console.error('parsing steps error')
    }
    try {
        // init envs
        let envsValue = envsInputs.value;
        if (envsValue && envsValue !== "None") {
            let envs = JSON.parse(envsValue);
            envs.forEach(e => {
                createEnvRow(e)
            })
        }
    } catch (e) {
        console.error('parsing envs error')
    }
    // attach submit form
    let buttonSubmit = document.getElementById('form_submit');
    buttonSubmit.addEventListener('click', function () {
        envsInputs.value = JSON.stringify(getEnvs());
        stepsInput.value = JSON.stringify(getSteps());
    })

</script>
<script>
    // listen to socket
    //
    const status = document.getElementById('running_status');
    const runSubmit = document.getElementById('run_pipeline');
    const isHidden = 'is-hidden';
    window.addEventListener('load', (event) => {
        console.log("DOMContentLoaded")
        window.HUB.on('status', function (payload) {
            console.log(payload);
            if (payload.is_running) {
                status.classList.remove(isHidden);
                runSubmit.setAttribute('disabled', 'disabled')
            } else {
                status.classList.add(isHidden);
                runSubmit.removeAttribute('disabled')
            }
        })
    });
</script>

{% endblock %}

templates/settings.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Setting</h3>
    <div class="box">
        <form method="POST" action="/settings">
            <div class="field">
                <div class="control">
                    <input class="input is-large" value="" type="text" name="gitlab_personal_token"
                           placeholder="gitlab personal Token"
                           autofocus="">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" value="" type="text" name="gitlab_webhook_token"
                           placeholder="gitlab webhook Token"
                           autofocus="">
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Save</button>
        </form>
    </div>
</div>
{% endblock %}